//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WOCreationSOAP", Namespace="http://www.example.org/WOCreation/")]
public partial class WOCreation : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback NewOperationOperationCompleted;
    
    /// <remarks/>
    public WOCreation() {
        this.Url = "http://csitosbprt.dev.hq.nwc:21303/NwcCompass/CCBEAMWorkOrderCreationSourceOSBPro" +
            "ject/CcbEamPSWorkOrderCreationSourceHttp";
    }
    
    /// <remarks/>
    public event NewOperationCompletedEventHandler NewOperationCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/WOCreation/NewOperation", RequestElementName="CM-EAMRequest", RequestNamespace="http://oracle.com/CM-EAMRequest.xsd", ResponseElementName="CM-EAMResponse", ResponseNamespace="http://oracle.com/CM-EAMResponse.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("responseCode")]
    public string NewOperation([System.Xml.Serialization.XmlElementAttribute("caseAttributes", typeof(CMEAMRequestCaseAttributes), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlElementAttribute("customerDetails", typeof(CMEAMRequestCustomerDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlElementAttribute("fieldActivityDetails", typeof(CMEAMRequestFieldActivityDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlElementAttribute("meterDetails", typeof(CMEAMRequestMeterDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlElementAttribute("serviceLocationDetails", typeof(CMEAMRequestServiceLocationDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object[] Items, out string responseDescription, [System.Xml.Serialization.XmlElementAttribute("fieldActivityDetails")] out CMEAMResponseFieldActivityDetails[] fieldActivityDetails, [System.Xml.Serialization.XmlElementAttribute("surveyDetails")] out CMEAMResponseSurveyDetails[] surveyDetails, [System.Xml.Serialization.XmlElementAttribute("installationDetails")] out CMEAMResponseInstallationDetails[] installationDetails, [System.Xml.Serialization.XmlElementAttribute("removalDetails")] out CMEAMResponseRemovalDetails[] removalDetails, [System.Xml.Serialization.XmlElementAttribute("readDetails")] out CMEAMResponseReadDetails[] readDetails) {
        object[] results = this.Invoke("NewOperation", new object[] {
                    Items});
        responseDescription = ((string)(results[1]));
        fieldActivityDetails = ((CMEAMResponseFieldActivityDetails[])(results[2]));
        surveyDetails = ((CMEAMResponseSurveyDetails[])(results[3]));
        installationDetails = ((CMEAMResponseInstallationDetails[])(results[4]));
        removalDetails = ((CMEAMResponseRemovalDetails[])(results[5]));
        readDetails = ((CMEAMResponseReadDetails[])(results[6]));
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginNewOperation(object[] Items, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("NewOperation", new object[] {
                    Items}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndNewOperation(System.IAsyncResult asyncResult, out string responseDescription, out CMEAMResponseFieldActivityDetails[] fieldActivityDetails, out CMEAMResponseSurveyDetails[] surveyDetails, out CMEAMResponseInstallationDetails[] installationDetails, out CMEAMResponseRemovalDetails[] removalDetails, out CMEAMResponseReadDetails[] readDetails) {
        object[] results = this.EndInvoke(asyncResult);
        responseDescription = ((string)(results[1]));
        fieldActivityDetails = ((CMEAMResponseFieldActivityDetails[])(results[2]));
        surveyDetails = ((CMEAMResponseSurveyDetails[])(results[3]));
        installationDetails = ((CMEAMResponseInstallationDetails[])(results[4]));
        removalDetails = ((CMEAMResponseRemovalDetails[])(results[5]));
        readDetails = ((CMEAMResponseReadDetails[])(results[6]));
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void NewOperationAsync(object[] Items) {
        this.NewOperationAsync(Items, null);
    }
    
    /// <remarks/>
    public void NewOperationAsync(object[] Items, object userState) {
        if ((this.NewOperationOperationCompleted == null)) {
            this.NewOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewOperationOperationCompleted);
        }
        this.InvokeAsync("NewOperation", new object[] {
                    Items}, this.NewOperationOperationCompleted, userState);
    }
    
    private void OnNewOperationOperationCompleted(object arg) {
        if ((this.NewOperationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.NewOperationCompleted(this, new NewOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CMEAMRequestCaseAttributes {
    
    private string caseDescriptionField;
    
    private string caseClassificationCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string caseDescription {
        get {
            return this.caseDescriptionField;
        }
        set {
            this.caseDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string caseClassificationCode {
        get {
            return this.caseClassificationCodeField;
        }
        set {
            this.caseClassificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CMEAMRequestCustomerDetails {
    
    private string entityNameField;
    
    private string identificationNumberField;
    
    private string customerClassField;
    
    private string cisDivisionField;
    
    private string homePhoneField;
    
    private string cellPhoneField;
    
    private string businessPhoneField;
    
    private string primaryPhoneField;
    
    private string faxNumberField;
    
    private string emailAddressField;
    
    private string lifeSupportSensitiveLoadField;
    
    private string avgConsumptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identificationNumber {
        get {
            return this.identificationNumberField;
        }
        set {
            this.identificationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerClass {
        get {
            return this.customerClassField;
        }
        set {
            this.customerClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cisDivision {
        get {
            return this.cisDivisionField;
        }
        set {
            this.cisDivisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string homePhone {
        get {
            return this.homePhoneField;
        }
        set {
            this.homePhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cellPhone {
        get {
            return this.cellPhoneField;
        }
        set {
            this.cellPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string businessPhone {
        get {
            return this.businessPhoneField;
        }
        set {
            this.businessPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string primaryPhone {
        get {
            return this.primaryPhoneField;
        }
        set {
            this.primaryPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string faxNumber {
        get {
            return this.faxNumberField;
        }
        set {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string emailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lifeSupportSensitiveLoad {
        get {
            return this.lifeSupportSensitiveLoadField;
        }
        set {
            this.lifeSupportSensitiveLoadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avgConsumption {
        get {
            return this.avgConsumptionField;
        }
        set {
            this.avgConsumptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CMEAMRequestFieldActivityDetails {
    
    private string fieldActivityIdField;
    
    private string eAMWorkCategoryField;
    
    private string eAMWorkTypeField;
    
    private string priorityField;
    
    private string scheduleDateTimeField;
    
    private string fieldActivityStatusField;
    
    private string instructionsField;
    
    private string commentsField;
    
    private string rescheduleReasonField;
    
    private string cancelReasonField;
    
    private string imagesURLField;
    
    private string assetNumberField;
    
    private string appSourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fieldActivityId {
        get {
            return this.fieldActivityIdField;
        }
        set {
            this.fieldActivityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EAMWorkCategory {
        get {
            return this.eAMWorkCategoryField;
        }
        set {
            this.eAMWorkCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EAMWorkType {
        get {
            return this.eAMWorkTypeField;
        }
        set {
            this.eAMWorkTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string scheduleDateTime {
        get {
            return this.scheduleDateTimeField;
        }
        set {
            this.scheduleDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fieldActivityStatus {
        get {
            return this.fieldActivityStatusField;
        }
        set {
            this.fieldActivityStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string instructions {
        get {
            return this.instructionsField;
        }
        set {
            this.instructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string rescheduleReason {
        get {
            return this.rescheduleReasonField;
        }
        set {
            this.rescheduleReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cancelReason {
        get {
            return this.cancelReasonField;
        }
        set {
            this.cancelReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string imagesURL {
        get {
            return this.imagesURLField;
        }
        set {
            this.imagesURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string assetNumber {
        get {
            return this.assetNumberField;
        }
        set {
            this.assetNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string appSource {
        get {
            return this.appSourceField;
        }
        set {
            this.appSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CMEAMRequestMeterDetails {
    
    private string badgeNumberField;
    
    private string serialNumberField;
    
    private string meterSizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string badgeNumber {
        get {
            return this.badgeNumberField;
        }
        set {
            this.badgeNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string meterSize {
        get {
            return this.meterSizeField;
        }
        set {
            this.meterSizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CMEAMRequestServiceLocationDetails {
    
    private string xyCoordinatesField;
    
    private string maintenanceAreaField;
    
    private string houseConnectionNumberField;
    
    private string meterReadInstructionField;
    
    private string districtStreetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xyCoordinates {
        get {
            return this.xyCoordinatesField;
        }
        set {
            this.xyCoordinatesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maintenanceArea {
        get {
            return this.maintenanceAreaField;
        }
        set {
            this.maintenanceAreaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string houseConnectionNumber {
        get {
            return this.houseConnectionNumberField;
        }
        set {
            this.houseConnectionNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string meterReadInstruction {
        get {
            return this.meterReadInstructionField;
        }
        set {
            this.meterReadInstructionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string districtStreet {
        get {
            return this.districtStreetField;
        }
        set {
            this.districtStreetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseFieldActivityDetails {
    
    private string fieldActivityIdField;
    
    private string eAMTransactionIdField;
    
    private string eAMWorkTypeField;
    
    private string eAMStatusField;
    
    private string startDateTimeField;
    
    private string completionDateTimeField;
    
    private string rescheduleReasonField;
    
    private string cancelReasonField;
    
    private string commentsField;
    
    private string priorityField;
    
    private string caseClassificationCodeField;
    
    private string cisDivisionField;
    
    private string houseConnectionNumberField;
    
    private string failureReasonField;
    
    /// <remarks/>
    public string fieldActivityId {
        get {
            return this.fieldActivityIdField;
        }
        set {
            this.fieldActivityIdField = value;
        }
    }
    
    /// <remarks/>
    public string EAMTransactionId {
        get {
            return this.eAMTransactionIdField;
        }
        set {
            this.eAMTransactionIdField = value;
        }
    }
    
    /// <remarks/>
    public string EAMWorkType {
        get {
            return this.eAMWorkTypeField;
        }
        set {
            this.eAMWorkTypeField = value;
        }
    }
    
    /// <remarks/>
    public string EAMStatus {
        get {
            return this.eAMStatusField;
        }
        set {
            this.eAMStatusField = value;
        }
    }
    
    /// <remarks/>
    public string startDateTime {
        get {
            return this.startDateTimeField;
        }
        set {
            this.startDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string completionDateTime {
        get {
            return this.completionDateTimeField;
        }
        set {
            this.completionDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string rescheduleReason {
        get {
            return this.rescheduleReasonField;
        }
        set {
            this.rescheduleReasonField = value;
        }
    }
    
    /// <remarks/>
    public string cancelReason {
        get {
            return this.cancelReasonField;
        }
        set {
            this.cancelReasonField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string caseClassificationCode {
        get {
            return this.caseClassificationCodeField;
        }
        set {
            this.caseClassificationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string cisDivision {
        get {
            return this.cisDivisionField;
        }
        set {
            this.cisDivisionField = value;
        }
    }
    
    /// <remarks/>
    public string houseConnectionNumber {
        get {
            return this.houseConnectionNumberField;
        }
        set {
            this.houseConnectionNumberField = value;
        }
    }
    
    /// <remarks/>
    public string failureReason {
        get {
            return this.failureReasonField;
        }
        set {
            this.failureReasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseSurveyDetails {
    
    private CMEAMResponseSurveyDetailsWaterConnectionAttributes[] waterConnectionAttributesField;
    
    private CMEAMResponseSurveyDetailsSewerConnectionAttributes[] sewerConnectionAttributesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("waterConnectionAttributes")]
    public CMEAMResponseSurveyDetailsWaterConnectionAttributes[] waterConnectionAttributes {
        get {
            return this.waterConnectionAttributesField;
        }
        set {
            this.waterConnectionAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sewerConnectionAttributes")]
    public CMEAMResponseSurveyDetailsSewerConnectionAttributes[] sewerConnectionAttributes {
        get {
            return this.sewerConnectionAttributesField;
        }
        set {
            this.sewerConnectionAttributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseSurveyDetailsWaterConnectionAttributes {
    
    private string averageConnectionSizeField;
    
    private string waterPipeLengthField;
    
    /// <remarks/>
    public string averageConnectionSize {
        get {
            return this.averageConnectionSizeField;
        }
        set {
            this.averageConnectionSizeField = value;
        }
    }
    
    /// <remarks/>
    public string waterPipeLength {
        get {
            return this.waterPipeLengthField;
        }
        set {
            this.waterPipeLengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseSurveyDetailsSewerConnectionAttributes {
    
    private string sewerPipeDiameterField;
    
    /// <remarks/>
    public string sewerPipeDiameter {
        get {
            return this.sewerPipeDiameterField;
        }
        set {
            this.sewerPipeDiameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseInstallationDetails {
    
    private string serialNumberField;
    
    private string meterTypeField;
    
    private string readDateTimeField;
    
    private string registerReadingField;
    
    /// <remarks/>
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string meterType {
        get {
            return this.meterTypeField;
        }
        set {
            this.meterTypeField = value;
        }
    }
    
    /// <remarks/>
    public string readDateTime {
        get {
            return this.readDateTimeField;
        }
        set {
            this.readDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string registerReading {
        get {
            return this.registerReadingField;
        }
        set {
            this.registerReadingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseRemovalDetails {
    
    private string serialNumberField;
    
    private string readDateTimeField;
    
    private string registerReadingField;
    
    /// <remarks/>
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string readDateTime {
        get {
            return this.readDateTimeField;
        }
        set {
            this.readDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string registerReading {
        get {
            return this.registerReadingField;
        }
        set {
            this.registerReadingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oracle.com/CM-EAMResponse.xsd")]
public partial class CMEAMResponseReadDetails {
    
    private string serialNumberField;
    
    private string readDateTimeField;
    
    private string registerReadingField;
    
    /// <remarks/>
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string readDateTime {
        get {
            return this.readDateTimeField;
        }
        set {
            this.readDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string registerReading {
        get {
            return this.registerReadingField;
        }
        set {
            this.registerReadingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void NewOperationCompletedEventHandler(object sender, NewOperationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NewOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal NewOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string responseDescription {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
    
    /// <remarks/>
    public CMEAMResponseFieldActivityDetails[] fieldActivityDetails {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CMEAMResponseFieldActivityDetails[])(this.results[2]));
        }
    }
    
    /// <remarks/>
    public CMEAMResponseSurveyDetails[] surveyDetails {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CMEAMResponseSurveyDetails[])(this.results[3]));
        }
    }
    
    /// <remarks/>
    public CMEAMResponseInstallationDetails[] installationDetails {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CMEAMResponseInstallationDetails[])(this.results[4]));
        }
    }
    
    /// <remarks/>
    public CMEAMResponseRemovalDetails[] removalDetails {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CMEAMResponseRemovalDetails[])(this.results[5]));
        }
    }
    
    /// <remarks/>
    public CMEAMResponseReadDetails[] readDetails {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CMEAMResponseReadDetails[])(this.results[6]));
        }
    }
}
