// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace nwc.Tarwya.Domain.Models.Models
{
    public partial class Area
    {
        public Area()
        {
            AreaCoordinates = new HashSet<AreaCoordinate>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<AreaCoordinate> AreaCoordinates { get; set; }
    }
}