// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace nwc.Tarwya.Domain.Models.Models
{
    public partial class AreaCoordinate
    {
        public int Id { get; set; }
        public int AreaId { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }

        public virtual Area Area { get; set; }
    }
}