//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nwc.Tarwya.Infra.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nwc.Tarwya.Infra.Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of reports submitted on this asset has been reached..
        /// </summary>
        public static string ComplaintLimitReached {
            get {
                return ResourceManager.GetString("ComplaintLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Answer all Feedback Questions.
        /// </summary>
        public static string CompleteFeedback {
            get {
                return ResourceManager.GetString("CompleteFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem creating your report, please try again later..
        /// </summary>
        public static string FaildCreateComplaint {
            get {
                return ResourceManager.GetString("FaildCreateComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of the asset to be reported is incorrect, please make sure to choose the correct asset number..
        /// </summary>
        public static string InValidAsset {
            get {
                return ResourceManager.GetString("InValidAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Available while hajj season only.
        /// </summary>
        public static string NoSeasons {
            get {
                return ResourceManager.GetString("NoSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear pilgrim,It is our pleasure to serve you through Tarwiah Mobile App.To raise complaints about toilets, please call KIDANA Development Company on . 920014234 .
        /// </summary>
        public static string WelcomeKedana {
            get {
                return ResourceManager.GetString("WelcomeKedana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no work order with this number, please make sure that the work order number is entered correctly..
        /// </summary>
        public static string WorkOrderNotFound {
            get {
                return ResourceManager.GetString("WorkOrderNotFound", resourceCulture);
            }
        }
    }
}
