//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECM_UploadService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECMUploadReposneStatus", Namespace="http://schemas.datacontract.org/2004/07/NWC.IT.ECM.UploadService")]
    public partial class ECMUploadReposneStatus : object
    {
        
        private string DocumentUrlField;
        
        private string FaultCodeField;
        
        private string FaultMessageField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentUrl
        {
            get
            {
                return this.DocumentUrlField;
            }
            set
            {
                this.DocumentUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage
        {
            get
            {
                return this.FaultMessageField;
            }
            set
            {
                this.FaultMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECMUploadFaultContract", Namespace="http://schemas.datacontract.org/2004/07/NWC.IT.ECM.UploadService")]
    public partial class ECMUploadFaultContract : object
    {
        
        private string FaultCodeField;
        
        private string FaultStringField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultString
        {
            get
            {
                return this.FaultStringField;
            }
            set
            {
                this.FaultStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECM_UploadService.IECMUploadService")]
    public interface IECMUploadService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMUploadService/UploadDocumentsToSPECM", ReplyAction="http://tempuri.org/IECMUploadService/UploadDocumentsToSPECMResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECM_UploadService.ECMUploadFaultContract), Action="http://tempuri.org/IECMUploadService/UploadDocumentsToSPECM", Name="ECMUploadFaultContract", Namespace="http://schemas.datacontract.org/2004/07/NWC.IT.ECM.UploadService")]
        System.Threading.Tasks.Task<ECM_UploadService.ECMUploadReposneStatus> UploadDocumentsToSPECMAsync(byte[] fileContent, string xmlMetadataInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IECMUploadServiceChannel : ECM_UploadService.IECMUploadService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ECMUploadServiceClient : System.ServiceModel.ClientBase<ECM_UploadService.IECMUploadService>, ECM_UploadService.IECMUploadService
    {
        
        public ECMUploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ECM_UploadService.ECMUploadReposneStatus> UploadDocumentsToSPECMAsync(byte[] fileContent, string xmlMetadataInfo)
        {
            return base.Channel.UploadDocumentsToSPECMAsync(fileContent, xmlMetadataInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
